import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind_Siliguri, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import QueryProviders from "@/providers/queryClient";
import MotionProvider from "@/providers/motion";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "sonner";
import ForbiddenToast from "@/components/ForbiddenToast";

const inter = Inter({ subsets: ["latin"], variable: "--font-latin" });

const hindSiliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["bengali"],
  variable: "--font-hind-siliguri",
  });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
        hindSiliguri.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <QueryProviders>
          <MotionProvider>
            <TooltipProvider>
              {children}
              <Toaster richColors position="top-right" />
              <ForbiddenToast />
            </TooltipProvider>
          </MotionProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
